export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },

  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCHED_MORE: "POST_DATA_FETCHED_MORE",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POPULAR_POST_DATA_DELETED",
    POPULAR_DATA_FETCHING: "POPULAR_POST_DATA_FETCHING",
    POPULAR_DATA_FETCHED: "POPULAR_POST_DATA_FETCHED",
    POPULAR_DATA_FETCH_ERROR: "POPULAR_POST_DATA_FETCH_ERROR",
  },
};
